export const SAVE_USER_DETAILS = "SAVE_USER_DETAILS";
export const SAVE_USER_WORKSPACE_DETAILS = "SAVE_USER_WORKSPACE_DETAILS";
export const SAVE_USER_USAGE = "SAVE_USER_USAGE";
export const SET_COMPLETED_STEPS = "SET_COMPLETED_STEPS";
